#################################################################
# Description: 
# Nvim configuration in Docker!
#################################################################
# To use: docker exec -it nvim-docker sh
#################################################################
                                                                                              
version: '3.7'
services:
  nvim-docker:
    container_name: nvim-docker-pde
    build:
      context: .
      dockerfile: Dockerfile.nvim
    volumes:
      - ./workspace:/home/dev/workspace
      - ./config:/root/.config/nvim
      - ./.bashrc:/root/.bashrc

